version: 0.2

phases:
  pre_build:
    commands:
      # Optional: Run any pre-build commands or scripts here
  build:
    commands:
      - npm ci
      - npm run build # Replace with the appropriate build command for your frontend project

artifacts:
  files:
    - '**/*'
  base-directory: build